typography_spectrum: 0.06652358965948224
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3514726215507835
  lightness: 0.03948742593638599
  saturation: 0.8217130086850375
  rhythmicContrast: 0.2807839694432914
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.73665
analytics:
  google: UA-76914704-1
  facebook: null
  twitter: null
name: datanews
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'News about Data Science, Machine Learning, Analytics and Python'
purpose: []
